### ISSUE TITLE
mac或无法工作？

### ISSUE THREAD

**Issue by oahgnod** [Henryhaohao/Bilibili_video_download#30]
程序无法运行，两个都尝试过，报错类似，如下：

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 82, in get_exe
    auto=False)
  File "/usr/local/lib/python3.7/site-packages/imageio/core/fetching.py", line 102, in get_remote_file
    raise NeedDownloadError()
imageio.core.fetching.NeedDownloadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bilibili_video_download_v1.py", line 16, in <module>
    from moviepy.editor import *
  File "/usr/local/lib/python3.7/site-packages/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 21, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 11, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python3.7/site-packages/moviepy/config.py", line 35, in <module>
    FFMPEG_BINARY = get_exe()
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:
  imageio.plugins.ffmpeg.download()

**Comment by Henryhaohao** [comment]
你看看这两篇文章解决一下试试: 
[https://blog.csdn.net/qq_41185868/article/details/79764062](url) ; 
[http://www.75271.com/19925.html](url) @oahgnod

**Comment by 1170300929** [comment]
用pip 安装试试，安装整个库吧



---原始邮件---
发件人: "王镇"<notifications@github.com&gt;
发送时间: 2019年10月11日(星期五) 下午4:04
收件人: "Henryhaohao/Bilibili_video_download"<Bilibili_video_download@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Henryhaohao/Bilibili_video_download] mac或无法工作？ (#30)



我的提示：
  
Imageio: 'ffmpeg.osx' was not found on your computer; downloading it now.
 Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg.osx (28.8 MB)
  
@Henryhaohao 请问 ffmpeg.osx 下载完成之后是放在那里？我手动下载玩了，通过终端自动下载总是出错

**Comment by 0wyh** [comment]
> 我的提示：
> 
> > Imageio: 'ffmpeg.osx' was not found on your computer; downloading it now.
> > Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg.osx (28.8 MB)
> 
> @Henryhaohao 请问 ffmpeg.osx 下载完成之后是放在那里？我手动下载完了，通过终端自动下载总是出错

Download from 的链接后面就是下载链接哦，下载完放在/Users/「此处替换成你的用户名」/Library/Application\ Support/imageio/ffmpeg
