### ISSUE TITLE
视频下不了报错了

### ISSUE THREAD

**Issue by sea13502** [Henryhaohao/Bilibili_video_download#45]
https://www.bilibili.com/video/av15057416?from=search&seid=11494394167082827401

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".\bilibili_video_download-GUI.py", line 236, in do_prepare
    combine_video(video_list, title)
  File ".\bilibili_video_download-GUI.py", line 160, in combine_video
    for file in sorted(os.listdir(root_dir), key=lambda x: int(x[x.rindex("-") + 1:x.rindex(".")])):
  File ".\bilibili_video_download-GUI.py", line 160, in <lambda>
    for file in sorted(os.listdir(root_dir), key=lambda x: int(x[x.rindex("-") + 1:x.rindex(".")])):
ValueError: substring not found

**Comment by sea13502** [comment]
不知道怎么回事，回退到这个版本531b9117f599101631620784c6927246d621dd9b就行了，借你的代码好好学学python

**Comment by sea13502** [comment]
https://www.bilibili.com/video/av15057416?from=search&seid=10099320395592303571   这个视频好像也报错~还有这个视频网站的视频机制，h5 video标签很神奇

**Comment by SunriseCai** [comment]
什么回事吖。？？怎么给我发了这么多邮件------------------ 原始邮件 ------------------
发件人: "hai"<notifications@github.com>
发送时间: 2019年8月2日(星期五) 中午1:29
收件人: "Henryhaohao/Bilibili_video_download"<Bilibili_video_download@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Henryhaohao/Bilibili_video_download] 视频下不了报错了 (#45)



不知道怎么回事，回退到这个版本531b9117f599101631620784c6927246d621dd9b就行了，借你的代码好好学学python
 
&mdash;

**Comment by Henryhaohao** [comment]
合并视频代码部分有点小问题, 现已修改, 可正常运行了, 感谢提出错误:heart:~ @sea13502

**Comment by sea13502** [comment]
👍👍👍
