### ISSUE TITLE
1 2 都不行

### ISSUE THREAD

**Issue by wanghaisheng** [Henryhaohao/Bilibili_video_download#49]
(py3.7) ➜  Bilibili_video_download git:(master) python bilibili_video_download_bangumi.py
******************************B站番剧视频下载小助手******************************
[提示]: 1.如果您想下载720P60,1080p+,1080p60质量的视频,请将35行代码中的SESSDATA改成你登录大会员后得到的SESSDATA,普通用户的SESSDATA最多只能下载1080p的视频
       2.若发现下载的视频质量在720p以下,请将35行代码中的SESSDATA改成你登录后得到的SESSDATA(有效期一个月),而失效的SESSDATA就只能下载480p的视频
请输入您要下载的B站番剧的完整链接地址(例如:https://www.bilibili.com/bangumi/play/ep267692):https://www.bilibili.com/video/av40280311/?p=1
请输入1或2 - 1.只下载当前一集 2.下载此番剧的全集:1
Traceback (most recent call last):
  File "bilibili_video_download_bangumi.py", line 202, in <module>
    id_list.append([ep_info['epInfo']['aid'], ep_info['epInfo']['cid'],
KeyError: 'epInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bilibili_video_download_bangumi.py", line 205, in <module>
    id_list.append([ep_info['epInfo']['aid'], ep_info['epInfo']['cid'],
KeyError: 'epInfo'

输入1 2 都会报同样的错

**Comment by Henryhaohao** [comment]
你好:
bilibili_video_download_bangumi.py这个是专门下载番剧视频的 ;
下载普通视频用bilibili_video_download_v3.py或者 bilibili_video_download-GUI.py这两个就好了
