### ISSUE TITLE
GUI版本无法正常使用

### ISSUE THREAD

**Issue by JustinZz1705** [Henryhaohao/Bilibili_video_download#54]
错误信息：
Traceback (most recent call last):
  File "D:\Bilibili_video_download-master\bilibili_video_download-GUI.py", line 268, in <module>
    root.iconbitmap('./Pic/favicon.ico')
  File "C:\WorkEnv\Python37\lib\tkinter\__init__.py", line 1871, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "./Pic/favicon.ico" not defined

**Comment by SunriseCai** [comment]
有病啊，次次都群发。去你的



---原始邮件---
发件人: "JustinZz1705"<notifications@github.com&gt;
发送时间: 2019年9月15日(星期日) 下午4:19
收件人: "Henryhaohao/Bilibili_video_download"<Bilibili_video_download@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Henryhaohao/Bilibili_video_download] GUI版本无法正常使用 (#54)



错误信息：
 Traceback (most recent call last):
 File "D:\Bilibili_video_download-master\bilibili_video_download-GUI.py", line 268, in 
 root.iconbitmap('./Pic/favicon.ico')
 File "C:\WorkEnv\Python37\lib\tkinter_init_.py", line 1871, in wm_iconbitmap
 return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
 _tkinter.TclError: bitmap "./Pic/favicon.ico" not defined

**Comment by JSbiu** [comment]
你需要把整个工程download下来,缺少Pic目录
