### ISSUE TITLE
下载这个视频时遇到报错，好多视频也是。。。。急急急。。

### ISSUE THREAD

**Issue by wangtesting** [Henryhaohao/Bilibili_video_download#75]
https://www.bilibili.com/video/av11182529
下载这个视频时遇到报错，好多视频也是。。。。急急急。。或者日后能增加下载弹幕的功能吗。
Traceback (most recent call last):
  File "D:/bilibilidown/Bilibili_video_download-master/bilibili_video_download_v3.py", line 232, in <module>
    combine_video(title_list)
  File "D:/bilibilidown/Bilibili_video_download-master/bilibili_video_download_v3.py", line 152, in combine_video
    for file in sorted(os.listdir(current_video_path), key=lambda x: int(x[x.rindex("-") + 1:x.rindex(".")])):
  File "D:/bilibilidown/Bilibili_video_download-master/bilibili_video_download_v3.py", line 152, in <lambda>
    for file in sorted(os.listdir(current_video_path), key=lambda x: int(x[x.rindex("-") + 1:x.rindex(".")])):
ValueError: substring not found

**Comment by dengmin** [comment]
http://bilibili.syyhc.com 可以帮到你
