### ISSUE TITLE
Error while fetching file: <urlopen error [Errno 111] Connection refused>.

### ISSUE THREAD

**Issue by jiangtao008** [Henryhaohao/Bilibili_video_download#92]
I run this program on the Ubuntu system. Now get the following error: 

```
python bilibili_video_download_v3-linux.py 
Imageio: 'ffmpeg.linux64' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [Errno 111] Connection refused>.
Error while fetching file: <urlopen error [Errno 111] Connection refused>.
Error while fetching file: <urlopen error [Errno 111] Connection refused>.
Error while fetching file: <urlopen error [Errno 111] Connection refused>.
Traceback (most recent call last):
  File "bilibili_video_download_v3-linux.py", line 21, in <module>
    imageio.plugins.ffmpeg.download()
  File "/home/tao/.local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 55, in download
    get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])
  File "/home/tao/.local/lib/python3.7/site-packages/imageio/core/fetching.py", line 121, in get_remote_file
    _fetch_file(url, filename)
  File "/home/tao/.local/lib/python3.7/site-packages/imageio/core/fetching.py", line 177, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg.linux64'. Perhaps there is a no internet connection? If there is, please report this problem.
```

Who can tell me what happened

**Comment by gpgzy** [comment]
I run this program on the Windows too.
