### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' 

### ISSUE THREAD

**Issue by icoo000** [Henryhaohao/Bilibili_video_download#98]
Traceback (most recent call last):
  File "E:\github_workspace\Bilibili_video_download\bilibili_video_download_v1.py", line 17, in <module>
    import requests, time, hashlib, urllib.request, re, json
  File "C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 29, in <module>
    from .connection import (
  File "C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\wait.py", line 1, in <module>
    from .selectors import (
  File "C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\shy_0\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

**Comment by selfuppen** [comment]
我的 mac，也遇到同样的问题：
```
➜  bili_download git:(master) python3 bilibili_video_download-GUI.py

Traceback (most recent call last):
  File "/Users/guoqiang/IdeaProjects/github/practice/bili_download/bilibili_video_download-GUI.py", line 15, in <module>
    import requests, time, hashlib, urllib.request, re, json
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

**Comment by DuckDuckFlash** [comment]
这个问题应该是python版本太高，3.8和3.9版本的貌似可以直接使用，想要在更高版本用的话，需要在最后提示的那个文件中把from collections import xxx改成from collections.abc import xxx需要改的文件数量有点多，慢慢改完就行。
要注意一点，现在b站视频都已经改成了bv号想要用这个下载要先转换成av号

**Comment by Ravanla** [comment]
@UnhappyMoonlight 我的38和39版本为啥不行的？大佬有解决方案吗？
![image](https://github.com/Henryhaohao/Bilibili_video_download/assets/44738145/c60356ce-5d96-49e5-a305-e039d097a0cc)
